### ISSUE TITLE
Problem with <link> tag

### ISSUE THREAD

**Issue by Guillaume-Fgt** [jsleroy/thirsty#2]
If you generate a gpx file with Brouter and use thirsty to add water points, you will get an error when you try to load the generated .gpx file as a track (and nothing happens if you load it as a route). If you delete the <link> tag inside the gpx file, all is working normally and water points are visible.

To reproduce it:
- save this file as .gpx:
```
<?xml version="1.0" encoding="UTF-8"?>
<!-- track-length = 766 filtered ascend = 4 plain-ascend = 1 cost=1871 energy=0.0kwh time=2m 17s -->
<gpx 
 xmlns="http://www.topografix.com/GPX/1/1" 
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd" 
 version="1.1" 
 creator="bikerouter.de 2025.26">
 <trk>
  <name>test</name>
  <link href="https://brouter.m11n.de/#map=16/48.6891/2.0214/standard&amp;lonlats=2.01505,48.690593;2.021533,48.686074">
   <text>bikerouter.de</text>
  </link>
  <trkseg>
   <trkpt lat="48.690576" lon="2.015081"><ele>110.5</ele></trkpt>
   <trkpt lat="48.690756" lon="2.015285"><ele>110.5</ele></trkpt>
   <trkpt lat="48.690741" lon="2.015327"><ele>110.75</ele></trkpt>
   <trkpt lat="48.690688" lon="2.015461"><ele>110.75</ele></trkpt>
   <trkpt lat="48.690568" lon="2.015584"><ele>110</ele></trkpt>
   <trkpt lat="48.690204" lon="2.015897"><ele>107.5</ele></trkpt>
   <trkpt lat="48.689626" lon="2.016365"><ele>105.25</ele></trkpt>
   <trkpt lat="48.689402" lon="2.016559"><ele>105.5</ele></trkpt>
   <trkpt lat="48.689278" lon="2.016627"><ele>105.5</ele></trkpt>
   <trkpt lat="48.688792" lon="2.016807"><ele>107</ele></trkpt>
   <trkpt lat="48.688589" lon="2.016927"><ele>108</ele></trkpt>
   <trkpt lat="48.688453" lon="2.017071"><ele>108.25</ele></trkpt>
   <trkpt lat="48.688319" lon="2.017263"><ele>109</ele></trkpt>
   <trkpt lat="48.688004" lon="2.017726"><ele>112</ele></trkpt>
   <trkpt lat="48.687571" lon="2.018253"><ele>113.75</ele></trkpt>
   <trkpt lat="48.687356" lon="2.018438"><ele>113.5</ele></trkpt>
   <trkpt lat="48.687329" lon="2.018408"><ele>113.75</ele></trkpt>
   <trkpt lat="48.68731" lon="2.0184"><ele>113.75</ele></trkpt>
   <trkpt lat="48.687282" lon="2.018404"><ele>113.75</ele></trkpt>
   <trkpt lat="48.687191" lon="2.018498"><ele>114.25</ele></trkpt>
   <trkpt lat="48.687177" lon="2.018525"><ele>114.25</ele></trkpt>
   <trkpt lat="48.687168" lon="2.018562"><ele>114.25</ele></trkpt>
   <trkpt lat="48.687167" lon="2.018606"><ele>114.25</ele></trkpt>
   <trkpt lat="48.687175" lon="2.018647"><ele>114</ele></trkpt>
   <trkpt lat="48.687198" lon="2.018692"><ele>113.75</ele></trkpt>
   <trkpt lat="48.687224" lon="2.018715"><ele>113.5</ele></trkpt>
   <trkpt lat="48.687247" lon="2.018722"><ele>113.25</ele></trkpt>
   <trkpt lat="48.686999" lon="2.019224"><ele>112.5</ele></trkpt>
   <trkpt lat="48.686882" lon="2.019483"><ele>112</ele></trkpt>
   <trkpt lat="48.686663" lon="2.019977"><ele>110</ele></trkpt>
   <trkpt lat="48.686621" lon="2.020082"><ele>109.75</ele></trkpt>
   <trkpt lat="48.686437" lon="2.020535"><ele>109.75</ele></trkpt>
   <trkpt lat="48.686129" lon="2.02157"><ele>111</ele></trkpt>
  </trkseg>
 </trk>
</gpx>
```
- run thirsty. It will find one water point
- try to load it in [Brouter](https://brouter.m11n.de/#map=16/48.6903/2.0200/standard) :
      * with load->load tracks. You will get a message "Error loading tracks: GeoJSON has no valid layers."
      * with load->load track as route. Nothing will happen.
 
If you edit the file manually by removing the <link> tag part, it will work as expected.

There is an issue opened on[ gpxpy](https://github.com/tkrajina/gpxpy/issues/283).

**Comment by jsleroy** [comment]
It should be fixed now.
Do you mind cross checking it works on your side, and if so, close the issue ?

**Comment by Guillaume-Fgt** [comment]
I still have the same problem. Updated to the latest commit. What did you change in the source code to solve the issue? 

Before:
```
  <link href="https://brouter.m11n.de/#map=17/48.68844/2.01832/standard&amp;lonlats=2.015272,48.690692;2.020369,48.68647">
   <text>bikerouter.de</text>
  </link>
```

After:
```
    <link href="https://brouter.m11n.de/#map=17/48.68844/2.01832/standard&lonlats=2.015272,48.690692;2.020369,48.68647">
      <text>bikerouter.de</text>
    </link>
```

![Image](https://github.com/user-attachments/assets/ce918bd7-ddcb-464f-90c7-1e007db61422)

After replacing the link part with the original one:

![Image](https://github.com/user-attachments/assets/11dbe6c6-623d-44b1-b1d5-a57c96c8d987)

**Comment by jsleroy** [comment]
Sorry, I forgot to push the commit.
Should be better now.

**Comment by Guillaume-Fgt** [comment]
Thank you, it works. 🔥 

I found an other way to avoid to regex all the file. The field `link` is in the Gpx class.
`gpx.tracks[0].link = sanitize_gpx_text(gpx.tracks[0].link)`

But not sure it's that important. I put it here for insight.
